spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/biapay
    username: bia_app
login:
  url: https://connect-dev.biapay.net/
redirect:
  url: https://connect-dev.biapay.net/verifyRegister/

StoreImages: /fileserver/store
biapay:
  upload-location: /fileserver/uploads
  enable-2fa: true
image:
  url: /fileserver/store

backoffice:
  domain: https://connect-dev.biapay.net


services:
  invoice:
    url: https://api-dev.biapay.net/invoice
  notification:
    pdf-file-path: /var/tmp/notifications
  websocket:
    url: https://websocket-dev.biapay.net

keycloak:
  realm: biapay
  auth-server-url: https://auth-dev.biapay.net
  resource: auth-service
  credentials:
    secret: cc6xkzPTPUi9JLpkxvBVDofvvo0muFU8
  ssl-required: none
  bearer-only: true

keycloak-config:
  admin:
    username: biapay_admin
    password: AYfASVncA#9tjVs2

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: https://eureka-dev.biapay.net/eureka
  instance:
    preferIpAddress: true
    hostname: localhost