spring:
  datasource:
    url: jdbc:postgresql://pgsql.biapay.net:5432/biapay_prod?currentSchema=biapay
    username: bia_app
    password: 7R?JMSy!pjt
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3

  kafka:
    bootstrap-servers: kafka.biapay.net:9092

login:
  url: https://connect.biapay.net
redirect:
  url: https://connect.biapay.net/verifyRegister/

StoreImages: /fileserver/store
biapay:
  upload-location: /fileserver/uploads
image:
  url: /fileserver/store

backoffice:
  domain: https://connect.biapay.net
  adminLogin: https://connect.biapay.net/adminLogin

referralService:
  url: https://api.biapay.net/referral
  referral-add-user-frequency: "0 0/1 * * * *"
  referral-reconciliation-frequency: "0 0/5 * * * *"

services:
  invoice:
    url: https://api.biapay.net/invoice
  notification:
    pdf-file-path: /var/tmp/notifications
  websocket:
    url: https://websocket.biapay.net/websocket

keycloak:
  realm: biapay
  auth-server-url: https://auth.biapay.net/
  resource: auth-service
  credentials:
    secret: oEELzbwomeYN1DCen4KMeAvGoAwmODI4
  ssl-required: none
  bearer-only: true

keycloak-config:
  admin:
    username: biapay_admin
    password: AYfASVncA#9tjVs2

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: https://eureka.biapay.net/eureka
  instance:
    preferIpAddress: true
    hostname: localhost