spring:
  datasource:
    password: mRb!3j^2&GS
    url: jdbc:postgresql://pgsql-dev.biapay.net:5432/biapay_dev?currentSchema=biapay
    username: bia_app
login:
  url: https://connect-dev.biapay.net/
redirect:
  url: https://connect-dev.biapay.net/verifyRegister/

StoreImages: /fileserver/store
biapay:
  upload-location: /fileserver/uploads
  enable-2fa: true

image:
  url: /fileserver/store

backoffice:
  domain: https://connect-dev.biapay.net
  adminLogin: https://connect-dev.biapay.net/adminLogin

services:
  invoice:
    url: https://api-dev.biapay.net/invoice
  websocket:
    url: https://websocket-dev.biapay.net


kyc-alert-config:
  frequency: "0 0 0 * * *"
  minDelayToStartAlertInDays: 3
  delayToInactivateMerchantInDays: 7
  delayToInactivateCustomerInDays: 30
  delayToSuspendMerchantInDays: 30
  delayToSuspendCustomerInDays: 60

keycloak:
  realm: biapay
  auth-server-url: https://auth-dev.biapay.net
  resource: auth-service
  credentials:
    secret: cc6xkzPTPUi9JLpkxvBVDofvvo0muFU8
  ssl-required: none
  bearer-only: true

keycloak-config:
  admin:
    username: biapay_admin
    password: AYfASVncA#9tjVs2

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: https://eureka-dev.biapay.net/eureka
  instance:
    preferIpAddress: true
    hostname: localhost